apiVersion: v1
kind: Service
metadata:
  name: tasky-new-action
spec:
  selector:
    app: tasky-new-action
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
