---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky-new-action
  labels:
    app: tasky-new-action
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasky-new-action
  template:
    metadata:
      labels:
        app: tasky-new-action
    spec:
      imagePullSecrets:
        - name: "regcred"
      containers:
        - name: tasky-new-action
          image: 442042516871.dkr.ecr.us-east-1.amazonaws.com/my-ecr-repo:latest
          env:
            - name: MONGODB_URI
              value: mongodb://admin:wiz2025@10.0.15.139:27017
            - name: SECRET_KEY
              value: secret123
          ports:
            - containerPort: 80
      serviceAccountName: godmode
